---
language: python
python: "2.7"
sudo: false

addons:
  apt:
    packages:
      - ansible

# https://github.com/ansible/ansible/blob/devel/lib/ansible/constants.py
env:
  global:
    - ANSIBLE_LIBRARY="/tmp/ansible/library"
    - ANSIBLE_ROLES_PATH="/tmp/ansible/roles"
    - ANSIBLE_LOCAL_TEMP="/tmp/ansible/cache"
    - ANSIBLE_REMOTE_TEMP="/tmp/ansible"
    - ANSIBLE_TRANSPORT=local
    - ANSIBLE_SSH_PIPELINING=True
    - ANSIBLE_HOST_KEY_CHECKING=False
    - ANSIBLE_DISPLAY_ARGS_TO_STDOUT=True
    - ANSIBLE_NO_LOG=True
    - ANSIBLE_NO_TARGET_SYSLOG=True
    - ANSIBLE_ASK_VAULT_PASS=False # TODO: somehow use `travis encrypt` for vault pass

before_install: 
  - mkdir -p "$ANSIBLE_LIBRARY" "$ANSIBLE_ROLES_PATH" "$ANSIBLE_LOCAL_TEMP"

install:
  # - printf '[defaults]\nroles_path=../' >ansible.cfg
  - ansible-galaxy install --ignore-errors -r requirements.yml
  
before_script:
  - ansible --version

script:
  - >
    find . -type f \( 
    -name "site.yml"
    -o -name ".travis.yml"
    -o -name "secrets.yml" 
    -o -name "cleanup.yml" 
    -o -name "requirements.yml"
    -o -name "ansible.yml" 
    -o -name "ssh.yml"
    -o -name "github.yml" 
    \) -prune 
    -o -name "*.yml" -print0 
    | xargs -0 ansible-playbook -l localhost
