---

- name: neovim
  src: https://github.com/templeman/ansible-neovim
# - src: dotstrap.dircolors
# - src: dotstrap.enhancd
# - src: dotstrap.fish
# - src: dotstrap.fzf
# - src: dotstrap.github
# - src: dotstrap.gnu-tools
# - src: dotstrap.neovim
# - src: dotstrap.node
# - src: dotstrap.macos
# - src: dotstrap.pure
# - src: dotstrap.ruby
# - src: dotstrap.sensible
# - src: dotstrap.ssh
# - src: dotstrap.xcode
# - src: dotstrap.xdg
# - src: dotstrap.j
